version: '3'

services:
  db:
    build:
      context: docker/db/
      dockerfile: Dockerfile
    container_name: picshare-database
    hostname: db
    volumes:
      - ./db:/var/lib/mysql
      - ./migrations:/migrations
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
